Data Cleaning, Missing Value Treatment

In [1]:
# Experiment No. 6

In [2]:
# Name :om s.chopar
# Roll : 69
# sec : A

In [3]:
# Aim : To perform Data Cleaning And Missing Value Treatment

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\chede appliances\\Downloads\\omdss'

In [7]:
os.chdir("D:\\Downloads")

In [9]:
df = pd.read_csv("test.csv")

In [10]:
df

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892811,1488022,0,1,6,0,0,0,1,0,0,...,4,2,3,4,0,1,0,0,1,0
892812,1488023,5,3,5,1,0,0,0,1,0,...,6,2,2,11,0,0,1,1,0,0
892813,1488024,0,1,5,0,0,1,0,0,0,...,5,2,2,11,0,1,1,0,0,0
892814,1488025,6,1,5,1,0,0,0,0,1,...,1,1,2,7,1,1,0,0,0,0
892815,1488026,7,1,4,1,0,0,0,0,1,...,5,2,2,7,0,1,1,1,0,0

In [11]:
df.head(15)

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1
5,5,0,1,6,0,0,1,0,0,0,...,8,1,4,9,1,0,1,0,1,0
6,6,0,1,3,0,0,0,1,0,0,...,2,0,4,6,1,1,0,0,0,0
7,8,0,1,0,0,0,1,0,0,0,...,3,1,4,9,0,1,0,0,0,0
8,10,0,1,7,0,0,0,1,0,0,...,5,1,4,6,0,0,1,0,0,0
9,11,1,1,6,0,0,0,0,0,1,...,6,1,6,10,0,1,1,0,0,0
10,12,0,1,5,0,4,1,0,0,0,...,2,1,1,8,0,1,1,1,0,0
11,14,1,1,4,0,0,1,0,0,0,...,4,2,7,8,0,1,0,1,0,0
12,15,1,1,2,1,0,0,1,0,0,...,3,4,0,12,1,1,0,0,1,0
13,18,3,1,3,0,0,0,1,0,0,...,7,0,5,9,0,0,0,1,0,0
14,21,0,2,1,0,6,1,0,0,0,...,6,3,5,6,0,0,1,0,0,0

In [12]:
df.tail(15)

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
892801,1488004,0,1,7,0,0,1,0,0,0,...,7,3,4,7,1,1,0,0,1,0
892802,1488006,2,1,2,1,0,0,1,0,0,...,6,1,3,10,0,1,1,0,1,0
892803,1488007,3,1,2,1,0,1,0,0,0,...,6,1,2,8,0,0,1,1,1,0
892804,1488010,4,1,6,0,0,1,0,0,0,...,5,0,3,10,0,1,1,1,1,0
892805,1488012,5,1,6,0,0,1,0,0,0,...,6,0,0,7,0,0,1,0,0,0
892806,1488014,0,1,6,1,0,1,0,0,0,...,5,2,5,10,0,0,1,1,0,0
892807,1488015,0,1,3,0,0,0,1,0,0,...,4,3,3,6,0,0,0,1,1,0
892808,1488018,1,1,6,0,4,1,0,0,0,...,7,1,2,4,0,0,1,1,1,0
892809,1488019,2,1,7,0,0,0,0,0,1,...,7,4,3,5,0,1,1,0,0,0
892810,1488020,0,1,6,0,0,0,0,0,1,...,2,3,5,7,0,1,1,1,1,1
892811,1488022,0,1,6,0,0,0,1,0,0,...,4,2,3,4,0,1,0,0,1,0
892812,1488023,5,3,5,1,0,0,0,1,0,...,6,2,2,11,0,0,1,1,0,0
892813,1488024,0,1,5,0,0,1,0,0,0,...,5,2,2,11,0,1,1,0,0,0
892814,1488025,6,1,5,1,0,0,0,0,1,...,1,1,2,7,1,1,0,0,0,0
892815,1488026,7,1,4,1,0,0,0,0,1,...,5,2,2,7,0,1,1,1,0,0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892816 entries, 0 to 892815
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              892816 non-null  int64
 1   ps_ind_01       892816 non-null  int64
 2   ps_ind_02_cat   892816 non-null  int64
 3   ps_ind_03       892816 non-null  int64
 4   ps_ind_04_cat   892816 non-null  int64
 5   ps_ind_05_cat   892816 non-null  int64
 6   ps_ind_06_bin   892816 non-null  int64
 7   ps_ind_07_bin   892816 non-null  int64
 8   ps_ind_08_bin   892816 non-null  int64
 9   ps_ind_09_bin   892816 non-null  int64
 10  ps_ind_10_bin   892816 non-null  int64
 11  ps_ind_11_bin   892816 non-null  int64
 12  ps_ind_12_bin   892816 non-null  int64
 13  ps_ind_13_bin   892816 non-null  int64
 14  ps_ind_14       892816 non-null  int64
 15  ps_ind_15       892816 non-null  int64
 16  ps_ind_16_bin   892816 non-null  int64
 17  ps_ind_17_bin   892816 non-null  int64
 18  ps_ind_18_bin   892816 non-null  int64
 19  ps_reg_01       892816 non-null  float64
 20  ps_reg_02       892816 non-null  float64
 21  ps_reg_03       892816 non-null  float64
 22  ps_car_01_cat   892816 non-null  int64
 23  ps_car_02_cat   892816 non-null  int64
 24  ps_car_03_cat   892816 non-null  int64
 25  ps_car_04_cat   892816 non-null  int64
 26  ps_car_05_cat   892816 non-null  int64
 27  ps_car_06_cat   892816 non-null  int64
 28  ps_car_07_cat   892816 non-null  int64
 29  ps_car_08_cat   892816 non-null  int64
 30  ps_car_09_cat   892816 non-null  int64
 31  ps_car_10_cat   892816 non-null  int64
 32  ps_car_11_cat   892816 non-null  int64
 33  ps_car_11       892816 non-null  int64
 34  ps_car_12       892816 non-null  float64
 35  ps_car_13       892816 non-null  float64
 36  ps_car_14       892816 non-null  float64
 37  ps_car_15       892816 non-null  float64
 38  ps_calc_01      892816 non-null  float64
 39  ps_calc_02      892816 non-null  float64
 40  ps_calc_03      892816 non-null  float64
 41  ps_calc_04      892816 non-null  int64
 42  ps_calc_05      892816 non-null  int64
 43  ps_calc_06      892816 non-null  int64
 44  ps_calc_07      892816 non-null  int64
 45  ps_calc_08      892816 non-null  int64
 46  ps_calc_09      892816 non-null  int64
 47  ps_calc_10      892816 non-null  int64
 48  ps_calc_11      892816 non-null  int64
 49  ps_calc_12      892816 non-null  int64
 50  ps_calc_13      892816 non-null  int64
 51  ps_calc_14      892816 non-null  int64
 52  ps_calc_15_bin  892816 non-null  int64
 53  ps_calc_16_bin  892816 non-null  int64
 54  ps_calc_17_bin  892816 non-null  int64
 55  ps_calc_18_bin  892816 non-null  int64
 56  ps_calc_19_bin  892816 non-null  int64
 57  ps_calc_20_bin  892816 non-null  int64
dtypes: float64(10), int64(48)
memory usage: 395.1 MB

In [14]:
df.shape

(892816, 58)

In [15]:
df.size

51783328

In [16]:
df.ndim

2

In [17]:
df.isna()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892811,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
892812,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
892813,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
892814,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
892815,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isna().any()

id                False
ps_ind_01         False
ps_ind_02_cat     False
ps_ind_03         False
ps_ind_04_cat     False
ps_ind_05_cat     False
ps_ind_06_bin     False
ps_ind_07_bin     False
ps_ind_08_bin     False
ps_ind_09_bin     False
ps_ind_10_bin     False
ps_ind_11_bin     False
ps_ind_12_bin     False
ps_ind_13_bin     False
ps_ind_14         False
ps_ind_15         False
ps_ind_16_bin     False
ps_ind_17_bin     False
ps_ind_18_bin     False
ps_reg_01         False
ps_reg_02         False
ps_reg_03         False
ps_car_01_cat     False
ps_car_02_cat     False
ps_car_03_cat     False
ps_car_04_cat     False
ps_car_05_cat     False
ps_car_06_cat     False
ps_car_07_cat     False
ps_car_08_cat     False
ps_car_09_cat     False
ps_car_10_cat     False
ps_car_11_cat     False
ps_car_11         False
ps_car_12         False
ps_car_13         False
ps_car_14         False
ps_car_15         False
ps_calc_01        False
ps_calc_02        False
ps_calc_03        False
ps_calc_04        False
ps_calc_05        False
ps_calc_06        False
ps_calc_07        False
ps_calc_08        False
ps_calc_09        False
ps_calc_10        False
ps_calc_11        False
ps_calc_12        False
ps_calc_13        False
ps_calc_14        False
ps_calc_15_bin    False
ps_calc_16_bin    False
ps_calc_17_bin    False
ps_calc_18_bin    False
ps_calc_19_bin    False
ps_calc_20_bin    False
dtype: bool

In [19]:
df.isna().sum()

id                0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0
ps_calc_12        0
ps_calc_13        0
ps_calc_14        0
ps_calc_15_bin    0
ps_calc_16_bin    0
ps_calc_17_bin    0
ps_calc_18_bin    0
ps_calc_19_bin    0
ps_calc_20_bin    0
dtype: int64

In [20]:
df.describe()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,8.928160e+05,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,...,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000,892816.000000
mean,7.441535e+05,1.902371,1.358613,4.413734,0.417361,0.408132,0.393246,0.257191,0.163659,0.185905,...,5.438478,1.440265,2.875013,7.540367,0.123720,0.627756,0.554660,0.287796,0.349344,0.152428
std,4.296830e+05,1.986503,0.663002,2.700149,0.493453,1.355068,0.488471,0.437086,0.369966,0.389030,...,2.330081,1.200620,1.694072,2.745882,0.329262,0.483403,0.497004,0.452736,0.476763,0.359435
min,0.000000e+00,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.720218e+05,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.443070e+05,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,1.116308e+06,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.488026e+06,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,...,20.000000,11.000000,15.000000,28.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [22]:
df["id"].fillna(30.272590)

0               0
1               1
2               2
3               3
4               4
           ...
892811    1488022
892812    1488023
892813    1488024
892814    1488025
892815    1488026
Name: id, Length: 892816, dtype: int64

In [23]:
df.isna().sum()

id                0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0
ps_calc_12        0
ps_calc_13        0
ps_calc_14        0
ps_calc_15_bin    0
ps_calc_16_bin    0
ps_calc_17_bin    0
ps_calc_18_bin    0
ps_calc_19_bin    0
ps_calc_20_bin    0
dtype: int64

In [24]:
df.any()

id                True
ps_ind_01         True
ps_ind_02_cat     True
ps_ind_03         True
ps_ind_04_cat     True
ps_ind_05_cat     True
ps_ind_06_bin     True
ps_ind_07_bin     True
ps_ind_08_bin     True
ps_ind_09_bin     True
ps_ind_10_bin     True
ps_ind_11_bin     True
ps_ind_12_bin     True
ps_ind_13_bin     True
ps_ind_14         True
ps_ind_15         True
ps_ind_16_bin     True
ps_ind_17_bin     True
ps_ind_18_bin     True
ps_reg_01         True
ps_reg_02         True
ps_reg_03         True
ps_car_01_cat     True
ps_car_02_cat     True
ps_car_03_cat     True
ps_car_04_cat     True
ps_car_05_cat     True
ps_car_06_cat     True
ps_car_07_cat     True
ps_car_08_cat     True
ps_car_09_cat     True
ps_car_10_cat     True
ps_car_11_cat     True
ps_car_11         True
ps_car_12         True
ps_car_13         True
ps_car_14         True
ps_car_15         True
ps_calc_01        True
ps_calc_02        True
ps_calc_03        True
ps_calc_04        True
ps_calc_05        True
ps_calc_06        True
ps_calc_07        True
ps_calc_08        True
ps_calc_09        True
ps_calc_10        True
ps_calc_11        True
ps_calc_12        True
ps_calc_13        True
ps_calc_14        True
ps_calc_15_bin    True
ps_calc_16_bin    True
ps_calc_17_bin    True
ps_calc_18_bin    True
ps_calc_19_bin    True
ps_calc_20_bin    True
dtype: bool

In [25]:
df = df.dropna()

In [26]:
df.any()

id                True
ps_ind_01         True
ps_ind_02_cat     True
ps_ind_03         True
ps_ind_04_cat     True
ps_ind_05_cat     True
ps_ind_06_bin     True
ps_ind_07_bin     True
ps_ind_08_bin     True
ps_ind_09_bin     True
ps_ind_10_bin     True
ps_ind_11_bin     True
ps_ind_12_bin     True
ps_ind_13_bin     True
ps_ind_14         True
ps_ind_15         True
ps_ind_16_bin     True
ps_ind_17_bin     True
ps_ind_18_bin     True
ps_reg_01         True
ps_reg_02         True
ps_reg_03         True
ps_car_01_cat     True
ps_car_02_cat     True
ps_car_03_cat     True
ps_car_04_cat     True
ps_car_05_cat     True
ps_car_06_cat     True
ps_car_07_cat     True
ps_car_08_cat     True
ps_car_09_cat     True
ps_car_10_cat     True
ps_car_11_cat     True
ps_car_11         True
ps_car_12         True
ps_car_13         True
ps_car_14         True
ps_car_15         True
ps_calc_01        True
ps_calc_02        True
ps_calc_03        True
ps_calc_04        True
ps_calc_05        True
ps_calc_06        True
ps_calc_07        True
ps_calc_08        True
ps_calc_09        True
ps_calc_10        True
ps_calc_11        True
ps_calc_12        True
ps_calc_13        True
ps_calc_14        True
ps_calc_15_bin    True
ps_calc_16_bin    True
ps_calc_17_bin    True
ps_calc_18_bin    True
ps_calc_19_bin    True
ps_calc_20_bin    True
dtype: bool

In [27]:
df.isna().sum()

id                0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0
ps_calc_12        0
ps_calc_13        0
ps_calc_14        0
ps_calc_15_bin    0
ps_calc_16_bin    0
ps_calc_17_bin    0
ps_calc_18_bin    0
ps_calc_19_bin    0
ps_calc_20_bin    0
dtype: int64